#:schema node_modules/wrangler/config-schema.json
name = "stuoa-api-web"
main = "src/index.js"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "stuoa-db-web"
database_id = "f476079e-50bc-45ba-8e64-61114da141a6"
